#!/usr/bin/env sh

echo "Running pre-push hook..."

export PYTHONUTF8=1
export PYTHONIOENCODING=utf-8

npm run semgrep
npm run trivy

echo "Running CodeQL..."
npm run codeql

echo "Running build..."
npm run build

echo "Pre-push checks passed."